Error while listening to messages: sent 1011 (internal error) keepalive ping timeout; no close frame received
Traceback (most recent call last):
  File "C:\Users\GaetanCORIN\Documents\btc_eth_streaming_data\.venv\Lib\site-packages\yfinance\live.py", line 295, in listen
    message = self._ws.recv()
              ^^^^^^^^^^^^^^^
  File "C:\Users\GaetanCORIN\Documents\btc_eth_streaming_data\.venv\Lib\site-packages\websockets\sync\connection.py", line 336, in recv
    raise self.protocol.close_exc from self.recv_exc
websockets.exceptions.ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received
Error while listening to messages: %s sent 1011 (internal error) keepalive ping timeout; no close frame received


Error while listening to messages: no close frame received or sent
Traceback (most recent call last):
  File "C:\Users\gaeta\Documents\btc_eth_streaming_data\.venv\Lib\site-packages\yfinance\live.py", line 295, in listen
    message = self._ws.recv()
              ^^^^^^^^^^^^^^^
  File "C:\Users\gaeta\Documents\btc_eth_streaming_data\.venv\Lib\site-packages\websockets\sync\connection.py", line 336, in recv
    raise self.protocol.close_exc from self.recv_exc
websockets.exceptions.ConnectionClosedError: no close frame received or sent
Error while listening to messages: %s no close frame received or sent


-----------------
Quand bug qui envoi vers csv, lorsque la connexion revient, il n arrive pas a se connecter
